### ISSUE TITLE
Kolejka

### ISSUE THREAD

**Issue by ptibbets** [omicronns/dd-project#6]
Jak tam Panie Szmit, jak postępy z kolejką?

**Comment by koxygen** [comment]
w sensie że zmerdżować czy coś?

**Comment by ptibbets** [comment]
Niekoniecznie, ale jak idzie dążenie do milestona?

**Comment by koxygen** [comment]
kolejka jest już gotowa, tylko nie jest zmergowana.
Mergowac?

**Comment by ptibbets** [comment]
Tylko weź najpierw pulla zrób na masterze

**Comment by koxygen** [comment]
done

**Comment by omicronns** [comment]
operator= powinien zwracać referencję, ponieważ w przeciwnym wypadku zwracana wartość nie jest lvalue.

**Comment by koxygen** [comment]
done
